export interface Question {
  id: string;
  text: string;
  options: string[];
  correct: number;
  xpReward: number;
}

export const QUESTIONS: Question[] = [
  // Easy Level
  {
    id: 'q1',
    text: 'Who built the ark?',
    options: ['Moses', 'Noah', 'Abraham', 'David'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q2',
    text: 'What did God create on the first day?',
    options: ['Animals', 'Light', 'Plants', 'Humans'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q3',
    text: 'Who was swallowed by a great fish?',
    options: ['Jonah', 'Paul', 'Peter', 'Job'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q4',
    text: 'Who led the Israelites out of Egypt?',
    options: ['Joshua', 'Moses', 'Aaron', 'David'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q5',
    text: 'What is the first book of the Bible?',
    options: ['Exodus', 'Genesis', 'Psalms', 'Matthew'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q6',
    text: 'Who was the first man?',
    options: ['Adam', 'Noah', 'Abraham', 'Isaac'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q7',
    text: 'Who was the first woman?',
    options: ['Sarah', 'Eve', 'Rachel', 'Hannah'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q8',
    text: 'What did Jesus turn water into?',
    options: ['Milk', 'Wine', 'Oil', 'Honey'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q9',
    text: 'Who betrayed Jesus?',
    options: ['Peter', 'Judas', 'Thomas', 'John'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q10',
    text: 'What is the shortest verse in the Bible?',
    options: ['"Jesus wept"', '"God is love"', '"Pray continually"', '"Fear not"'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q11',
    text: 'Who killed Goliath?',
    options: ['Saul', 'David', 'Samson', 'Solomon'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q12',
    text: 'What did God use to guide the Israelites at night?',
    options: ['Fire', 'Cloud', 'Star', 'Angel'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q13',
    text: 'Who was Abraham\'s wife?',
    options: ['Sarah', 'Rebekah', 'Rachel', 'Leah'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q14',
    text: 'How many disciples did Jesus have?',
    options: ['10', '12', '14', '7'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q15',
    text: 'Who was thrown into the lions\' den?',
    options: ['Daniel', 'Joseph', 'Elijah', 'Moses'],
    correct: 0,
    xpReward: 20,
  },
  // Medium Level
  {
    id: 'q16',
    text: 'Who interpreted Pharaoh\'s dreams?',
    options: ['Daniel', 'Joseph', 'Moses', 'Samuel'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q17',
    text: 'What was Ruth\'s mother-in-law\'s name?',
    options: ['Naomi', 'Sarah', 'Esther', 'Hannah'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q18',
    text: 'Who was the strongest man in the Bible?',
    options: ['Samson', 'David', 'Saul', 'Gideon'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q19',
    text: 'Who was the first king of Israel?',
    options: ['Saul', 'David', 'Solomon', 'Samuel'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q20',
    text: 'Who denied Jesus three times?',
    options: ['Judas', 'Peter', 'John', 'Thomas'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q21',
    text: 'Who was the father of John the Baptist?',
    options: ['Zechariah', 'Joseph', 'Simeon', 'Nicodemus'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q22',
    text: 'What city did the walls fall after marching around it?',
    options: ['Jericho', 'Nineveh', 'Babylon', 'Jerusalem'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q23',
    text: 'Who was the wisest king of Israel?',
    options: ['Saul', 'David', 'Solomon', 'Hezekiah'],
    correct: 2,
    xpReward: 20,
  },
  {
    id: 'q24',
    text: 'Who was thrown into a fiery furnace?',
    options: ['Shadrach, Meshach, Abednego', 'Daniel', 'Joseph', 'Elijah'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q25',
    text: 'Who was the tax collector that climbed a tree to see Jesus?',
    options: ['Zacchaeus', 'Matthew', 'Levi', 'Simon'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q26',
    text: 'Who was the prophet taken up to heaven in a whirlwind?',
    options: ['Elijah', 'Elisha', 'Isaiah', 'Jeremiah'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q27',
    text: 'Who was the disciple known as "Doubting"?',
    options: ['Peter', 'Thomas', 'Andrew', 'Philip'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q28',
    text: 'What river was Jesus baptized in?',
    options: ['Jordan', 'Nile', 'Euphrates', 'Tigris'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q29',
    text: 'Who was the first martyr in the New Testament?',
    options: ['Stephen', 'James', 'Paul', 'Peter'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q30',
    text: 'Who wrote most of the Psalms?',
    options: ['David', 'Solomon', 'Moses', 'Asaph'],
    correct: 0,
    xpReward: 20,
  },
  // Hard Level
  {
    id: 'q31',
    text: 'Which prophet confronted King Ahab on Mount Carmel?',
    options: ['Isaiah', 'Elijah', 'Elisha', 'Jeremiah'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q32',
    text: 'How many horsemen are described in Revelation?',
    options: ['3', '4', '5', '7'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q33',
    text: 'Who was the high priest when Jesus was crucified?',
    options: ['Caiaphas', 'Annas', 'Gamaliel', 'Nicodemus'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q34',
    text: 'Who was the prophet that married a prostitute as a sign to Israel?',
    options: ['Hosea', 'Amos', 'Micah', 'Joel'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q35',
    text: 'What was Paul\'s original name?',
    options: ['Saul', 'Simon', 'Levi', 'Barnabas'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q36',
    text: 'Who was the king who saw the writing on the wall?',
    options: ['Nebuchadnezzar', 'Belshazzar', 'Darius', 'Cyrus'],
    correct: 1,
    xpReward: 20,
  },
  {
    id: 'q37',
    text: 'Who was the prophet that saw dry bones come to life?',
    options: ['Ezekiel', 'Isaiah', 'Jeremiah', 'Daniel'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q38',
    text: 'Who was the prophet that said "Here am I, send me"?',
    options: ['Isaiah', 'Jeremiah', 'Amos', 'Micah'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q39',
    text: 'Who was the queen that visited Solomon?',
    options: ['Queen of Sheba', 'Esther', 'Jezebel', 'Athaliah'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q40',
    text: 'Who was the prophet that confronted David about Bathsheba?',
    options: ['Nathan', 'Samuel', 'Gad', 'Elijah'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q41',
    text: 'Who was the prophet that saw a vision of a flying scroll?',
    options: ['Zechariah', 'Malachi', 'Habakkuk', 'Joel'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q42',
    text: 'Who was the prophet that said "The just shall live by faith"?',
    options: ['Habakkuk', 'Hosea', 'Amos', 'Micah'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q43',
    text: 'Who was the prophet that saw a vision of a wheel within a wheel?',
    options: ['Ezekiel', 'Isaiah', 'Daniel', 'Jeremiah'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q44',
    text: 'Who was the prophet that confronted Nineveh?',
    options: ['Jonah', 'Nahum', 'Micah', 'Amos'],
    correct: 0,
    xpReward: 20,
  },
  {
    id: 'q45',
    text: 'Who was the prophet that saw the valley of vision?',
    options: ['Isaiah', 'Jeremiah', 'Ezekiel', 'Daniel'],
    correct: 0,
    xpReward: 20,
  },
];

export const DAILY_CREDITS = 100;
export const GAME_COST = 20;
export const TIME_LIMIT = 10; // seconds per question
